"""
PROJECT: CyberScan - Multi-Threaded GUI Port Scanner with Export
DESCRIPTION:
    A network discovery tool that identifies open TCP ports and 
    exports findings to a text file for documentation.
"""

import socket      # Handles low-level networking (TCP connections)
import threading   # Manages concurrent tasks (scanning multiple ports at once)
import tkinter as tk 
from tkinter import scrolledtext, messagebox # UI components for text display and alerts
from datetime import datetime # Generates timestamps for filenames and reports

def start_scan():
    """
    Initiates the scanning process. To keep the GUI from freezing, 
    it launches the scan logic in a background manager thread.
    """
    def scan_logic():
        # Retrieve the user-entered IP or Hostname from the entry box
        target = ip_entry.get()
        start_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Display initial status in the UI
        result_display.insert(tk.END, f"--- Starting Scan on {target} ---\n")
        
        def scan_port(port):
            """
            The worker function: Attempts a TCP Three-Way Handshake with a port.
            """
            try:
                # AF_INET = IPv4; SOCK_STREAM = TCP (standard connection-oriented)
                s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                
                # If no response in 0.5s, the port is likely filtered/closed
                s.settimeout(0.5)
                
                # connect_ex returns 0 if successful (Port is OPEN)
                if s.connect_ex((target, port)) == 0:
                    # .after(0, ...) ensures UI updates happen safely on the main thread
                    window.after(0, lambda p=port: result_display.insert(tk.END, f"[+] Port {p} is OPEN\n"))
                
                s.close() # Clean up the socket connection
            except:
                pass # Silent fail if the port is unreachable

        # 2. Multi-threading loop: Spawns 500 mini-tasks simultaneously
        # This makes the scan roughly 500x faster than a single-threaded loop
        for port in range(1, 501):
            t = threading.Thread(target=scan_port, args=(port,))
            t.start()
        
        # Post a completion message once all threads have been launched
        window.after(0, lambda: result_display.insert(tk.END, "--- Scan Complete ---\n"))

    # 3. daemon=True means the scanner stops immediately if you close the app window
    threading.Thread(target=scan_logic, daemon=True).start()

def save_report():
    """
    Exports the text inside the result_display box into a .txt file.
    """
    # Grab all text from the start (1.0) to the end (tk.END)
    report_content = result_display.get(1.0, tk.END)
    
    # Check if there is actual data (prevents saving empty files)
    if len(report_content.strip()) < 10:
        messagebox.showwarning("Warning", "No scan data to save!")
        return

    # Create a unique filename based on the current date and time
    filename = f"scan_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    
    try:
        # Standard Python file handling: 'w' for write mode
        with open(filename, "w") as f:
            f.write(f"CYBERSCAN REPORT\nGenerated by: Gian Carlo Miguel\n")
            f.write("-" * 30 + "\n")
            f.write(report_content)
        
        # Pop-up confirmation for the user
        messagebox.showinfo("Success", f"Report saved as: {filename}")
    except Exception as e:
        messagebox.showerror("Error", f"Failed to save report: {e}")

# --- GUI LAYOUT CONFIGURATION ---

window = tk.Tk()
window.title("CyberScan Pro")
window.geometry("400x600")

# Input field for target IP
tk.Label(window, text="Target IP Address:").pack(pady=10)
ip_entry = tk.Entry(window)
ip_entry.insert(0, "127.0.0.1") # Default to scanning the local machine
ip_entry.pack(pady=5)

# Horizontal frame to hold buttons side-by-side
btn_frame = tk.Frame(window)
btn_frame.pack(pady=10)

# Green 'Start' button
scan_btn = tk.Button(btn_frame, text="Start Scan", command=start_scan, bg="green", fg="white", width=12)
scan_btn.pack(side=tk.LEFT, padx=5)

# Blue 'Save' button
save_btn = tk.Button(btn_frame, text="Save Report", command=save_report, bg="blue", fg="white", width=12)
save_btn.pack(side=tk.LEFT, padx=5)

# ScrolledText widget allows user to scroll through long scan results
result_display = scrolledtext.ScrolledText(window, width=45, height=25)
result_display.pack(pady=10)

# The 'mainloop' keeps the window visible and responsive to clicks
window.mainloop()